# Generated by Django 4.2.5 on 2024-07-18 06:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название тура')),
                ('title_ru', models.CharField(max_length=70, null=True, verbose_name='Название тура')),
                ('title_en', models.CharField(max_length=70, null=True, verbose_name='Название тура')),
                ('title_ky', models.CharField(max_length=70, null=True, verbose_name='Название тура')),
                ('region', models.CharField(max_length=255, verbose_name='Область и Страна')),
                ('region_ru', models.CharField(max_length=255, null=True, verbose_name='Область и Страна')),
                ('region_en', models.CharField(max_length=255, null=True, verbose_name='Область и Страна')),
                ('region_ky', models.CharField(max_length=255, null=True, verbose_name='Область и Страна')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('max_people', models.PositiveIntegerField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('time', models.CharField(max_length=100)),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Просмотры')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.date', verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тег')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Тег')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Тег')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в избранное')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='game_images/', verbose_name='Изображение')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Format: '+996XXXXXXXXX'. Up to 12 digits allowed.", regex='^\\+996\\d{9}$')], verbose_name='Номер Телефона')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('date', models.DateField(verbose_name='Дата')),
                ('people_count', models.PositiveIntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Количество человек')),
                ('status', models.CharField(choices=[('pending', 'Не рассмотрено'), ('reviewed', 'Рассмотрено')], default='pending', max_length=50, verbose_name='Статус')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.tags', verbose_name='Теги'),
        ),
    ]
