version: "3"
services:
  history-postgres:
    image: postgres
    container_name: history-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build: .
    container_name: history
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/back-static
      - media_volume:/usr/src/app/back-media
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - history-postgres
      - redis
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: history-postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  celery:
    build: .
    container_name: celery
    volumes:
      - .:/app
    command: celery -A config worker --loglevel=info
    depends_on:
      - history-postgres
      - redis
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: history-postgres
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx_ssl.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/back-static
      - media_volume:/usr/src/app/back-media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
