INSTALLED_APPS = [
    "jazzmin",
    "modeltranslation",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    "django.contrib.flatpages",
    
    'django_seed',
    'drf_spectacular',
    "rest_framework",
    "django_filters",
    "corsheaders",
    "googletrans",
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth', 
    'dj_rest_auth.registration', 
    'rest_framework.authtoken',
    'ckeditor',
    'ckeditor_uploader',

    'users',
    'apps.games',
]